name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        platform: [linux, darwin, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build
        run: CGO_ENABLED=1 GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -ldflags="-X main.version=$(git rev-parse --short HEAD) -linkmode external -extldflags '-static' -s -w" -o migrash-${{ matrix.platform }}-${{ matrix.arch }}
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: migrash-${{ matrix.platform }}-${{ matrix.arch }}
          path: migrash-${{ matrix.platform }}-${{ matrix.arch }}
