name: publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        platform: [linux, darwin, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build
        run: GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -ldflags="-X main.version=$(git describe --tags --abbrev=0)" -o migrash-${{ matrix.platform }}-${{ matrix.arch }}
      - name: Archive
        uses: softprops/action-gh-release@v2
        with:
          files: |
            migrash-${{ matrix.platform }}-${{ matrix.arch }}
